apiVersion: apps/v1

kind: Deployment

metadata:
  name: maven-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: maven-app

  template:
    metadata:
      labels:
        app: maven-app

    spec:
      containers:
      - name: maven-app
        image: ranveer0318/maven-mssql-app:1.0

        ports:
        - containerPort: 8080
